# whitelist (branches that should be built)
branches:
  only:
    - master
    - /^issue.*$/

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode9
      sudo: required
    - os: linux
      dist: trusty
      sudo: required
      env: SWIFT_SNAPSHOT=3.1.1
    - os: osx
      osx_image: xcode8.3
      sudo: required
      env: SWIFT_SNAPSHOT=3.1.1
   
script:
  - ./Package-Builder/build-package.sh -projectDir $TRAVIS_BUILD_DIR 
